version: '3.9'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: nichijou_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data # <名前付きvolume名>:マウントしたいコンテナ内のPATH
  web:
    build: .
    command: ./bin/dev
    tty: true
    stdin_open: true
    volumes:
      - .:/nichijou
    ports:
      - "80:3000"
    depends_on:
      - db
volumes:
  pgdata: # 名前付きvolumeを定義

