default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: nichijou_pass
  pool: 5

development:
  <<: *default
  database: nichijou_development

test:
  <<: *default
  database: nichijou_test

production:
  <<: *default
  database: nichijou_production
  username: <%= ENV["NICHIJOU_DATABASE_USER"] %>
  password: <%= ENV["NICHIJOU_DATABASE_PASSWORD"] %>
