# 名前の定義。このCIジョブの名前を「Rails CI」としています。
name: Rails CI

# このCIジョブが実行されるトリガーを定義。
on:
  push:  # ブランチにプッシュされたときの動作を定義。
    branches:  # 以下のブランチにプッシュされた場合にCIジョブを実行。
      - nichijou_v1
      - master
  pull_request:  # プルリクエストが作成されたときの動作を定義。
    branches:  # 以下のブランチをターゲットとするプルリクエストでCIジョブを実行。
      - nichijou_v1
      - master

# 実行するジョブのリストを定義。
jobs:
  # rubocopジョブの定義。コードのスタイルチェックを行います。
  rubocop:
    runs-on: ubuntu-latest  # 実行環境として最新のUbuntuを使用。
    steps:  # このジョブで実行するステップのリスト。
      - name: Checkout code  # ソースコードをチェックアウトする。
        uses: actions/checkout@v2
      - name: Set up Ruby  # Rubyの環境をセットアップ。
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.1
      - name: Install dependencies  # 必要な依存関係をインストール。
        run: |
          gem install bundler
          bundle install
      - name: Run Rubocop  # Rubocopを実行してコードのスタイルチェック。
        run: bundle exec rubocop

  # brakemanジョブの定義。セキュリティの脆弱性チェックを行います。
  brakeman:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.1
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Run Brakeman  # Brakemanを実行してセキュリティチェック。
        run: bundle exec brakeman
